# Generated by Django 5.1 on 2024-08-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firstName",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
