# Generated by Django 5.1 on 2024-08-13 09:34

import django.db.models.deletion
import django.utils.crypto
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_password_user_rename_password_password_pwd_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashed_key", models.CharField(max_length=255)),
                (
                    "salt",
                    models.CharField(
                        default=django.utils.crypto.get_random_string, max_length=255
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PasswordEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("encrypted_password", models.TextField()),
                ("encryption_algorithm", models.CharField(max_length=50)),
                (
                    "salt",
                    models.CharField(
                        default=django.utils.crypto.get_random_string, max_length=32
                    ),
                ),
                ("iv_or_nonce", models.TextField()),
                ("encrypted_key", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
