# Generated by Django 5.1 on 2024-08-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_delete_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterkey",
            name="salt",
            field=models.CharField(
                default="B2VsiQ766LHclBP8faCQPSIhNnAGhUm6", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="salt",
            field=models.CharField(
                default="FJijZwhrpwZwvxMbsS55Yj3tFe3i5JUx", max_length=32
            ),
        ),
    ]
