# Generated by Django 5.1 on 2024-08-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_masterkey_salt_alter_passwordentry_salt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterkey",
            name="salt",
            field=models.CharField(
                default="E1V2pCjX5Tuwa04I8BXeuI3dFEK1oAgJ", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="salt",
            field=models.CharField(
                default="Iim84fhzvnOKrtOVKpbIPkTiIcKfiSC2", max_length=32
            ),
        ),
    ]
