# Generated by Django 5.1 on 2024-08-19 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_masterkey_salt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterkey",
            name="salt",
            field=models.CharField(
                default="QtHpwPjTXS0b2yNmOMFvCDnuao6MH6fh", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="salt",
            field=models.CharField(
                default="LTbubgt8TPw4AVgUavVMUo10iZCgQodG", max_length=32
            ),
        ),
        migrations.CreateModel(
            name="EncryptedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("encrypted_file", models.FileField(upload_to="encrypted_files/")),
                ("salt", models.CharField(max_length=64)),
                ("iv_or_nonce", models.CharField(max_length=64)),
                ("algorithm", models.CharField(default="AES", max_length=10)),
                ("encrypted_key", models.TextField(max_length=32)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
