# Generated by Django 5.1 on 2024-08-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_masterkey_salt_alter_passwordentry_salt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedfile",
            name="file_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="masterkey",
            name="salt",
            field=models.CharField(
                default="A2MObI47lDZvf0m2NMw4oBUh5Z6ALjZr", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="salt",
            field=models.CharField(
                default="uQGx40ob3ZbXsQYr9QR4p1jAKNRi91My", max_length=32
            ),
        ),
    ]
