# Generated by Django 5.1 on 2024-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_encryptedfile_file_path_alter_masterkey_salt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterkey",
            name="salt",
            field=models.CharField(
                default="7eBA3dvdwrRYh52KCvli8yI7yxz98jXH", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="salt",
            field=models.CharField(
                default="aYDy8ls0vrjb8dUv9ZDjeHWnRYJdPP0C", max_length=32
            ),
        ),
    ]
