# Generated by Django 5.1 on 2024-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_masterkey_salt_alter_passwordentry_salt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterkey",
            name="salt",
            field=models.CharField(
                default="fQHDi8z1Wmfkf5wUkS7kzDCrdFGMEwFR", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="salt",
            field=models.CharField(
                default="PFHs1TejZVjAhsF7BeUTrmLroJTxjTr6", max_length=32
            ),
        ),
    ]
