# Generated by Django 5.1 on 2024-08-21 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_alter_masterkey_salt_alter_passwordentry_salt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterkey",
            name="salt",
            field=models.CharField(
                default="GQ0tTLbrzYGKSFDKwTQSwELMYlEOnuAa", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="salt",
            field=models.CharField(
                default="AJ5MaLcL6oCdcZzQPJY8dt6Nhj4etu50", max_length=32
            ),
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Claro"),
                            ("dark", "Oscuro"),
                            ("pink", "Rosa"),
                        ],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("require_password_modify", models.BooleanField(default=True)),
                ("require_password_delete", models.BooleanField(default=True)),
                (
                    "notifications",
                    models.CharField(
                        choices=[
                            ("enabled", "Activadas"),
                            ("disabled", "Desactivadas"),
                        ],
                        default="enabled",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
