# Generated by Django 5.1 on 2025-08-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_alter_masterkey_salt_alter_passwordentry_salt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterkey",
            name="salt",
            field=models.CharField(
                default="yGaSjAeYfSKm1TnfD6G1CpqNVAgzFpkT", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="salt",
            field=models.CharField(
                default="z5BNme00mkVrzwHEQFcHym4NU7UpcXlZ", max_length=32
            ),
        ),
    ]
