# Generated by Django 5.1 on 2025-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_masterkey_salt_alter_passwordentry_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkey',
            name='salt',
            field=models.CharField(default='qwyKOm4SBhQWKGquYhKhIvim5y4BUqFi', max_length=32),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='salt',
            field=models.CharField(default='ExqX3fsb48r3t5xpxDi4PZZAozaqBdhw', max_length=32),
        ),
    ]
