# Generated by Django 5.1 on 2025-08-26 01:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_masterkey_salt_alter_passwordentry_salt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='masterkey',
            name='salt',
            field=models.CharField(default='Ubx0oR1lefpc00ncoUTh4B931YYEyyEU', max_length=32),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='salt',
            field=models.CharField(default='5TN2Ow0RD8ujHb9rfbUgaoZj10Re7382', max_length=32),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('password_created', 'Contraseña Creada'), ('password_updated', 'Contraseña Actualizada'), ('password_deleted', 'Contraseña Eliminada'), ('file_uploaded', 'Archivo Subido'), ('file_downloaded', 'Archivo Descargado'), ('file_deleted', 'Archivo Eliminado'), ('login', 'Inicio de Sesión'), ('settings_updated', 'Configuración Actualizada')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('success', 'Éxito'), ('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error')], default='info', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
