# Generated by Django 5.1 on 2025-08-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_encryptedfile_updated_at_passwordentry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkey',
            name='salt',
            field=models.CharField(default='BwGBE8N1NvIH1IHByCVyZ4ZraheDhc93', max_length=32),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='salt',
            field=models.CharField(default='INH6CouOQBLsu6R5fb1g8rIZDslSiseb', max_length=32),
        ),
    ]
