# Generated by Django 5.1 on 2025-09-01 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_masterkey_salt_alter_passwordentry_salt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failed_login', 'Intento de Login Fallido'), ('multiple_failed_logins', 'Múltiples Intentos Fallidos'), ('master_key_failed', 'Fallo de Clave Maestra'), ('suspicious_activity', 'Actividad Sospechosa'), ('decryption_failure', 'Error de Desencriptación'), ('unauthorized_access', 'Acceso No Autorizado')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('password_created', 'Contraseña Creada'), ('password_updated', 'Contraseña Actualizada'), ('password_deleted', 'Contraseña Eliminada'), ('password_viewed', 'Contraseña Visualizada'), ('file_uploaded', 'Archivo Subido'), ('file_downloaded', 'Archivo Descargado'), ('file_deleted', 'Archivo Eliminado'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('settings_updated', 'Configuración Actualizada'), ('master_key_created', 'Clave Maestra Creada'), ('master_key_verified', 'Clave Maestra Verificada'), ('security_analysis', 'Análisis de Seguridad')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='severity',
            field=models.CharField(choices=[('success', 'Éxito'), ('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='masterkey',
            name='salt',
            field=models.CharField(default='CJ7cCgfKOEym55J4s3Edr6oPABZO76y7', max_length=32),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='salt',
            field=models.CharField(default='aey2iDKM1nB2QRsb0JLuSncwz85Urszi', max_length=32),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='myapp_activ_user_id_461950_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'activity_type'], name='myapp_activ_user_id_0de8a1_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['severity', 'timestamp'], name='myapp_activ_severit_9c13a7_idx'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='myapp_secur_event_t_f01c75_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', 'timestamp'], name='myapp_secur_user_id_2715ac_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['resolved', 'timestamp'], name='myapp_secur_resolve_584a55_idx'),
        ),
    ]
