# Generated by Django 5.1 on 2025-09-05 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_securityevent_activitylog_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkey',
            name='salt',
            field=models.CharField(default='EZ64Xqy0G3aqlBxmYAJUolK6uOW7sooI', max_length=32),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='salt',
            field=models.CharField(default='VM3SMJJz4SG0QgnqCH971ndUK94qvU8z', max_length=32),
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('red', 'Rojo'), ('yellow', 'Amarillo'), ('purple', 'Morado'), ('orange', 'Naranja'), ('pink', 'Rosa'), ('gray', 'Gris')], default='blue', max_length=10)),
                ('is_private', models.BooleanField(default=False)),
                ('vault_password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('vault_salt', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwords', to='myapp.vault'),
        ),
        migrations.AddIndex(
            model_name='vault',
            index=models.Index(fields=['user', 'name'], name='myapp_vault_user_id_593f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='vault',
            index=models.Index(fields=['user', 'is_private'], name='myapp_vault_user_id_5e9aba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vault',
            unique_together={('user', 'name')},
        ),
    ]
