# Generated by Django 5.1 on 2025-09-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_masterkey_salt_alter_passwordentry_salt_vault_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('password_created', 'Contraseña Creada'), ('password_updated', 'Contraseña Actualizada'), ('password_deleted', 'Contraseña Eliminada'), ('password_viewed', 'Contraseña Visualizada'), ('file_uploaded', 'Archivo Subido'), ('file_downloaded', 'Archivo Descargado'), ('file_deleted', 'Archivo Eliminado'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('settings_updated', 'Configuración Actualizada'), ('master_key_created', 'Clave Maestra Creada'), ('master_key_verified', 'Clave Maestra Verificada'), ('security_analysis', 'Análisis de Seguridad'), ('vault_created', 'Vault Creado'), ('vault_updated', 'Vault Actualizado'), ('vault_deleted', 'Vault Eliminado'), ('vault_unlocked', 'Vault Desbloqueado'), ('password_moved', 'Contraseña Movida')], max_length=30),
        ),
        migrations.AlterField(
            model_name='masterkey',
            name='salt',
            field=models.CharField(default='o1XeSHppaj2ijlX1uDlIJIBO6dUV7B82', max_length=32),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='salt',
            field=models.CharField(default='s3L20WTpILkTCvaq86m4TVADUBocju1U', max_length=32),
        ),
    ]
