"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from os import path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


def _env_bool(name, default="false"):
    """Lee un booleano del entorno. Todo lo que no sea 1/true/yes/on es False."""
    return os.getenv(name, default).strip().lower() in ("1", "true", "yes", "on")


def _env_list(name, default=""):
    """Lee una lista separada por comas del entorno, ignorando entradas vacías."""
    return [v.strip() for v in os.getenv(name, default).split(",") if v.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
# Sin fallback a propósito (Fase 0, C5): si falta, Django debe fallar al arrancar
# en lugar de firmar los JWT con una clave pública conocida.
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", "false")

SESSION_TIMEOUT_MINUTES = 60
SESSION_TIMEOUT = SESSION_TIMEOUT_MINUTES * 60  # 3600 segundos


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_vite",
    "django_prometheus",
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_ratelimit',
    "corsheaders",  
    "myapp",
    
]

MIDDLEWARE = [
    # CORS debe ir PRIMERO
    'corsheaders.middleware.CorsMiddleware',
    
    # Security después de CORS
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    # Middleware personalizado de seguridad
    'myapp.middleware.SecurityLoggingMiddleware',
    'myapp.middleware.RateLimitMiddleware',
    
    # Middleware estándar Django
    'django.contrib.sessions.middleware.SessionMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # JWT después de auth estándar
    'myapp.middleware.JWTAuthenticationMiddleware',
    
    # ===== MIDDLEWARE DE SESIONES AVANZADAS =====
    'myapp.middleware.EnhancedSessionTrackingMiddleware',
    'myapp.middleware.SessionSecurityMiddleware',
    'myapp.middleware.SessionCreationMiddleware',
    'myapp.middleware.SessionCleanupMiddleware',
    
    # Resto de middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'myapp.middleware.AuditMiddleware',
]

ROOT_URLCONF = "demo.urls"

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "demo.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv('POSTGRES_DB', 'mydb'),
        "USER": os.getenv('POSTGRES_USER', 'myuser'),
        "PASSWORD": os.getenv('POSTGRES_PASSWORD', 'password'),
        "HOST": os.getenv('DB_HOST', 'db'),  # ← CAMBIADO: 'db' en Docker, 'localhost' en desarrollo local
        "PORT": os.getenv('DB_PORT', '5432'),
    }
}

# CONFIGURACIÓN DE REST FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Límites mucho más generosos para operaciones normales
        'anon': '1000/hour',        # Era 100/hour
        'user': '10000/hour',       # Era 1000/hour
        
        # Límites específicos para autenticación (mantener restrictivos)
        'login': '10/minute',       # Era 5/minute - un poco más permisivo
        'register': '5/minute',     # Era 3/minute - un poco más permisivo
        'password_reset': '3/minute',
        
        # Nuevos límites para operaciones específicas
        'upload': '50/hour',        # Para subida de archivos
        'download': '200/hour',     # Para descarga de archivos
        'api_data': '2000/hour',    # Para endpoints de datos del cliente
        'search': '500/hour',       # Para búsquedas
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        'OPTIONS': {
            'min_length': 12,  # Más estricto que 8
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        'NAME': 'myapp.validators.CustomPasswordValidator',  # Validador personalizado
    },
]

# Configuración de sesiones
# IMPORTANTE: Para que CORS funcione con CSRF
# TLS DESACOPLADO de DEBUG (Fase 0, C5). Motivo: nginx hoy sólo escucha en :80 y no
# envía X-Forwarded-Proto, así que activar SECURE_SSL_REDIRECT sin TLS real produce
# un bucle de redirección infinito. Se pondrá a true en la Fase 1, con el TLS de nginx.
_TLS = _env_bool("DJANGO_TLS_ENABLED", "false")

CSRF_COOKIE_HTTPONLY = False  # ¡Cambio crítico! Debe ser False para CORS
CSRF_COOKIE_SECURE = _TLS
CSRF_COOKIE_SAMESITE = 'Lax'    # Cambiar de 'Strict' a 'Lax' para CORS
CSRF_USE_SESSIONS = False      # Cambiar a False para CORS con frontend separado
CSRF_COOKIE_MASKED = True

# Configuración de cookies de sesión compatible
SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = _TLS
SESSION_COOKIE_SAMESITE = 'Lax'  # También cambiar a 'Lax'
SESSION_COOKIE_AGE = SESSION_TIMEOUT
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CONFIGURACIÓN DE HEADERS DE SEGURIDAD
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

if _TLS:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



SIMPLE_JWT = {
    # Hacer que JWT dure lo mismo que las sesiones
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=SESSION_TIMEOUT_MINUTES),  # 60 minutos
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # 7 días para refresh
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 300,  # 5 minutos de margen para evitar problemas de sincronización

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    
    # Tokens deslizantes para renovación automática
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=SESSION_TIMEOUT_MINUTES),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),

    'TOKEN_OBTAIN_SERIALIZER': 'myapp.serializers.CustomTokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',
}

# CONFIGURACIÓN DE LÍMITES DE VELOCIDAD
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'

# CONFIGURACIÓN MÁS GRANULAR - Solo para funciones específicas
CUSTOM_RATE_LIMITS = {
    # Autenticación - Restrictivo
    'auth_login': '10/5m',           # 10 intentos cada 5 minutos
    'auth_register': '5/10m',        # 5 registros cada 10 minutos
    'auth_password_reset': '3/10m',  # 3 resets cada 10 minutos
    'auth_token_refresh': '20/5m',   # 20 refreshes cada 5 minutos
    
    # Operaciones de archivo - Moderado
    'file_upload': '20/10m',         # 20 uploads cada 10 minutos
    'file_download': '100/10m',      # 100 downloads cada 10 minutos
    
    # APIs de datos - Muy permisivo
    'data_fetch': '1000/10m',        # 1000 requests cada 10 minutos
    'search_api': '500/10m',         # 500 búsquedas cada 10 minutos
    
    # Operaciones críticas - Restrictivo
    'admin_actions': '10/10m',       # 10 acciones admin cada 10 minutos
    'sensitive_data': '50/10m',      # 50 requests a datos sensibles cada 10 minutos
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Para mantener la autenticación por nombre de usuario
    'myapp.authentication.EmailBackend',  # Agrega aquí tu backend de email
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "staticfiles/"
STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ← CORREGIDO: Solo incluir directorios que existen
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'),
]

# ← AGREGAR CONDICIONALMENTE si el directorio existe
if os.path.exists(BASE_DIR / "static" / "dist"):
    STATICFILES_DIRS.append(BASE_DIR / "static" / "dist")

# Gobernado por entorno (Fase 0, C5). '0.0.0.0' se elimina a propósito: es una
# dirección de escucha, no un host válido, y como comodín sólo añadía superficie.
ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,web")
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configuración para django-vite
DJANGO_VITE_ASSETS_PATH = BASE_DIR / "static" / "dist"
DJANGO_VITE_DEV_MODE = _env_bool("DJANGO_VITE_DEV_MODE", "false")
DJANGO_VITE_DEV_SERVER_HOST = "localhost"
DJANGO_VITE_DEV_SERVER_PORT = 5173

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = _env_list("CORS_ALLOWED_ORIGINS", "http://localhost:5174")
CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS", "http://localhost:5174")


# Headers permitidos
# Headers permitidos - añadir todos los necesarios
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'content-disposition',
    'cache-control',
]

CORS_EXPOSE_HEADERS = [
    'Content-Disposition',
    'Content-Type',
    'Content-Length',
    'X-CSRFToken',

]


MINIO_ENDPOINT = os.getenv('MINIO_ENDPOINT', 'minio:9000')
MINIO_ACCESS_KEY = os.getenv('MINIO_ACCESS_KEY')
MINIO_SECRET_KEY = os.getenv('MINIO_SECRET_KEY')
MINIO_BUCKET_NAME = os.getenv('MINIO_BUCKET_NAME', 'user-encrypted-files')
MINIO_USE_SSL = os.getenv('MINIO_USE_SSL', 'false').lower() == 'true'

# Reemplaza la sección LOGGING en tu settings.py con esta versión corregida:

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
        'security': {
            # CORREGIDO: Solo usar campos que existen en LogRecord
            'format': '[{levelname}] {asctime} - {name} - {message}',
            'style': '{',
        },
        'audit': {
            # CORREGIDO: Eliminar campos personalizados que no existen
            'format': '[AUDIT] {asctime} - {name} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'infrastructure/logs/django/security.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'security',
        },
        'audit_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'infrastructure/logs/django/audit.log',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'audit',
        },
        'auth_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'infrastructure/logs/django/auth.log',
            'maxBytes': 5242880,  # 5MB
            'backupCount': 3,
            'formatter': 'security',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'audit': {
            'handlers': ['audit_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'auth': {
            'handlers': ['auth_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'session': {
            'handlers': ['audit_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Silenciar algunos logs verbosos en desarrollo
        'django.db.backends': {
            'level': 'ERROR',
            'handlers': ['console'],
            'propagate': False,
        },
    },
}

# 8. CONFIGURACIÓN DE CACHE PARA RATE LIMITING
REDIS_URL = os.getenv('REDIS_URL', 'redis://redis:6379/1')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'retry_on_timeout': True,
                'health_check_interval': 30,
                'max_connections': 20,
            },
            'IGNORE_EXCEPTIONS': True,  # No fallar si Redis no está disponible
        },
        'TIMEOUT': 300,  # 5 minutos por defecto
        'KEY_PREFIX': 'myapp_session',  # Prefijo para evitar colisiones
        'VERSION': 1,
    },
    # Cache secundario para session activities (opcional)
    'sessions': {
        'BACKEND': 'django_redis.cache.RedisCache',
        # Variable propia: antes leía REDIS_URL con un default engañoso, así que
        # en cuanto REDIS_URL estaba definida ambas cachés compartían la db 1.
        'LOCATION': os.getenv('REDIS_SESSIONS_URL', 'redis://redis:6379/2'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,
        },
        'TIMEOUT': 43200,  # 12 horas para sesiones
        'KEY_PREFIX': 'session_data',
    }
}

# Configuración del SessionManager
MAX_SESSIONS_PER_USER =  5
SESSION_RENEWAL_THRESHOLD = SESSION_TIMEOUT_MINUTES * 60 // 2 # 30 minutos

# Configuración de seguridad de sesiones
STRICT_IP_CHECKING = os.getenv('STRICT_IP_CHECKING', 'false').lower() == 'true'
SESSION_SECURITY_ENABLED = True
SESSION_CLEANUP_ENABLED = True

SESSION_CLEANUP_CRON = {
    'ENABLED': os.getenv('SESSION_CLEANUP_CRON_ENABLED', 'true').lower() == 'true',
    'INTERVAL_MINUTES': int(os.getenv('SESSION_CLEANUP_INTERVAL', 60)),  # Cada hora
}


# CONFIGURACIÓN DE ENCRIPTACIÓN PARA ARCHIVOS
ENCRYPTION_KEY_ROTATION_DAYS = 90
MAX_FAILED_LOGIN_ATTEMPTS = 5
LOCKOUT_DURATION_MINUTES = 30
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB max
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880   # 5MB max

# CONFIGURACIÓN DE MONITOREO
SECURITY_MIDDLEWARE = {
    'LOG_SUSPICIOUS_REQUESTS': True,
    'BLOCK_SUSPICIOUS_IPS': True,
    'MAX_REQUEST_SIZE': 1024 * 1024 * 10,  # 10MB
}

SECURITY_ALERTS = {
    'ENABLED': os.getenv('SECURITY_ALERTS_ENABLED', 'true').lower() == 'true',
    'EMAIL_NOTIFICATIONS': os.getenv('SECURITY_EMAIL_ALERTS', 'false').lower() == 'true',
    'SLACK_NOTIFICATIONS': os.getenv('SECURITY_SLACK_ALERTS', 'false').lower() == 'true',
    'WEBHOOK_URL': os.getenv('SECURITY_WEBHOOK_URL', ''),
}

SESSION_MONITORING = {
    'TRACK_USER_AGENTS': True,
    'TRACK_IP_CHANGES': True,
    'TRACK_LOCATION_CHANGES': True,
    'ALERT_ON_SUSPICIOUS_ACTIVITY': True,
    'MAX_CONCURRENT_SESSIONS': MAX_SESSIONS_PER_USER,
}

# Clave propia: antes caía en ENCRYPTION_KEY, reutilizando la misma clave para
# dos dominios distintos (datos de sesión y objetos de MinIO).
SESSION_ENCRYPTION_KEY = os.getenv('SESSION_ENCRYPTION_KEY', '')


TRUSTED_DEVICES = {
    'ENABLED': True,
    'TRUST_DURATION_DAYS': int(os.getenv('TRUSTED_DEVICE_DAYS', 30)),
    'REQUIRE_2FA_FOR_NEW_DEVICES': os.getenv('REQUIRE_2FA_NEW_DEVICES', 'true').lower() == 'true',
}
