# Generated by Django 5.1 on 2024-08-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_masterkey_passwordentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Password",
        ),
    ]
