# Generated by Django 5.1 on 2024-08-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_masterkey_salt_alter_passwordentry_salt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterkey",
            name="salt",
            field=models.CharField(
                default="xPk2RnqY3tgaTP6AnRbjikFNHczqdf8p", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="encrypted_key",
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="iv_or_nonce",
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="salt",
            field=models.CharField(
                default="R9MCC8xM4SAs0891iGB6BBFqDU9hjZ3b", max_length=32
            ),
        ),
    ]
